// ConfigGen — reads the authoritative build-time config database (sqldoc.db)
// and emits typed Swift into Sources/SQLDocCore/Generated/.
//
//   swift run ConfigGen [--db sqldoc.db] [--out Sources/SQLDocCore/Generated] [--platform mac]
//
// Invoked by `make generate`. The generated files are committed; `make
// config-check` fails if they drift from the database. See docs/build-config.md.

import Foundation
import SQLite3

// MARK: - args

var dbPath = "sqldoc.db"
var outDir = "Sources/SQLDocCore/Generated"
var platform = "mac"
var plistPath = ""   // when set, also render a macOS Info.plist there
do {
    var it = CommandLine.arguments.dropFirst().makeIterator()
    while let a = it.next() {
        switch a {
        case "--db":       dbPath = it.next() ?? dbPath
        case "--out":      outDir = it.next() ?? outDir
        case "--platform": platform = it.next() ?? platform
        case "--plist":    plistPath = it.next() ?? plistPath
        default: FileHandle.standardError.write(Data("ConfigGen: unknown arg \(a)\n".utf8)); exit(2)
        }
    }
}

// MARK: - tiny sqlite reader

final class DB {
    private var handle: OpaquePointer?
    init(_ path: String) {
        guard sqlite3_open_v2(path, &handle, SQLITE_OPEN_READONLY, nil) == SQLITE_OK else {
            fail("cannot open \(path): \(String(cString: sqlite3_errmsg(handle)))")
        }
    }
    deinit { sqlite3_close(handle) }

    /// Runs `sql` and returns rows as ordered [(column, value?)] dictionaries keyed by name.
    func rows(_ sql: String) -> [[String: String?]] {
        var stmt: OpaquePointer?
        guard sqlite3_prepare_v2(handle, sql, -1, &stmt, nil) == SQLITE_OK else {
            fail("bad query: \(sql)\n\(String(cString: sqlite3_errmsg(handle)))")
        }
        defer { sqlite3_finalize(stmt) }
        let ncol = sqlite3_column_count(stmt)
        var out: [[String: String?]] = []
        while sqlite3_step(stmt) == SQLITE_ROW {
            var row: [String: String?] = [:]
            for i in 0..<ncol {
                let name = String(cString: sqlite3_column_name(stmt, i))
                if sqlite3_column_type(stmt, i) == SQLITE_NULL {
                    row[name] = String?.none
                } else if let c = sqlite3_column_text(stmt, i) {
                    row[name] = String(cString: c)
                } else {
                    row[name] = String?.none
                }
            }
            out.append(row)
        }
        return out
    }
}

func fail(_ m: String) -> Never {
    FileHandle.standardError.write(Data("ConfigGen: \(m)\n".utf8)); exit(1)
}

// MARK: - helpers

/// "window.block_rows" / "col-min-width" / "bundle_id.viewer" -> "windowBlockRows" ...
func camel(_ s: String) -> String {
    let parts = s.split(whereSeparator: { $0 == "." || $0 == "_" || $0 == "-" })
    guard let first = parts.first else { return s }
    return ([first.lowercased()] + parts.dropFirst().map { $0.capitalized }).joined()
}

func numeric(_ s: String) -> String {
    let t = s.trimmingCharacters(in: CharacterSet(charactersIn: " px%x"))
    return t.contains(".") || t.isEmpty ? (t.isEmpty ? "0" : t) : t
}

func swiftString(_ s: String) -> String {
    "\"" + s.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\"") + "\""
}

let db = DB(dbPath)
let schemaVersion = db.rows("SELECT value FROM meta WHERE key='schema_version'").first?["value"] as? String ?? "?"

func header(_ what: String) -> String {
    """
    // Generated by ConfigGen from sqldoc.db (schema v\(schemaVersion), platform \(platform)).
    // DO NOT EDIT. Regenerate with `make generate`. Source of truth: config/*.sql.
    // \(what)

    """
}

let fm = FileManager.default
try? fm.createDirectory(atPath: outDir, withIntermediateDirectories: true)
func write(_ file: String, _ body: String) {
    let path = "\(outDir)/\(file)"
    try! body.data(using: .utf8)!.write(to: URL(fileURLWithPath: path))
    print("wrote \(path)")
}

// MARK: - BehaviorConfig.swift

do {
    var out = header("Behaviour / engine tunables (the `setting` table).")
    out += "import Foundation\n\npublic enum BehaviorConfig {\n"
    for r in db.rows("SELECT key,value,value_type,unit,min_value,max_value,description FROM v_setting_resolved WHERE platform=\(swiftString(platform)) ORDER BY key") {
        let key = r["key"]!!, value = r["value"]!!, type = r["value_type"]!!
        let unit = (r["unit"] ?? "") ?? "", desc = (r["description"] ?? "") ?? ""
        let lo = (r["min_value"] ?? "") ?? "", hi = (r["max_value"] ?? "") ?? ""
        let bound = (lo.isEmpty && hi.isEmpty) ? "" : "  [\(lo.isEmpty ? "…" : lo)..\(hi.isEmpty ? "…" : hi)\(unit.isEmpty ? "" : " " + unit)]"
        let (swiftType, literal): (String, String)
        switch type {
        case "int", "duration": (swiftType, literal) = ("Int", numeric(value))
        case "float":           (swiftType, literal) = ("Double", value.contains(".") ? value : value + ".0")
        case "bool":            (swiftType, literal) = ("Bool", value)
        default:                (swiftType, literal) = ("String", swiftString(value))
        }
        if !desc.isEmpty || !bound.isEmpty { out += "    /// \(desc)\(bound)\n" }
        out += "    public static let \(camel(key)): \(swiftType) = \(literal)\n"
    }
    out += "}\n"
    write("BehaviorConfig.swift", out)
}

// MARK: - DesignTokens.swift

do {
    var out = header("Design tokens (the `token` table): colours, dimensions, durations, numbers.")
    out += """
    import CoreGraphics
    import Foundation

    /// A colour token with its light and dark hex strings. Map to a platform
    /// colour type in the UI layer (see AppTheme).
    public struct ColorToken: Sendable, Equatable {
        public let light: String
        public let dark: String
        public init(light: String, dark: String) { self.light = light; self.dark = dark }
    }

    public enum DesignToken {

    """
    for r in db.rows("SELECT name,category,unit,value_light,value_dark,overridable,description FROM v_token_resolved WHERE platform=\(swiftString(platform)) ORDER BY sort_order, name") {
        let name = r["name"]!!, category = r["category"]!!
        let light = r["value_light"]!!, dark = (r["value_dark"] ?? light) ?? light
        let desc = (r["description"] ?? "") ?? ""
        let over = ((r["overridable"] ?? "0") ?? "0") == "1"
        if !desc.isEmpty { out += "    /// \(desc)\(over ? "  (a document _style may override this)" : "")\n" }
        switch category {
        case "color":
            out += "    public static let \(camel(name)) = ColorToken(light: \(swiftString(light)), dark: \(swiftString(dark)))\n"
        case "dimension":
            out += "    public static let \(camel(name)): CGFloat = \(numeric(light))\n"
        case "duration":
            out += "    public static let \(camel(name)) = Duration.milliseconds(\(numeric(light)))\n"
        default: // opacity | number
            out += "    public static let \(camel(name)): Double = \(light.contains(".") ? light : light + ".0")\n"
        }
    }
    // convenience: plain hex of the accent for `Style` defaults
    if let accent = db.rows("SELECT value_light FROM v_token_resolved WHERE platform=\(swiftString(platform)) AND name='accent'").first?["value_light"] as? String {
        out += "\n    /// Bare hex string of the default accent, for Style() defaults.\n"
        out += "    public static let accentHex = \(swiftString(accent))\n"
    }
    out += "}\n"
    write("DesignTokens.swift", out)
}

// MARK: - AppIdentity.swift

do {
    var out = header("Application identity (the `identity` table).")
    out += "import Foundation\n\npublic enum AppIdentity {\n"
    for r in db.rows("SELECT key,value,description FROM v_identity WHERE platform=\(swiftString(platform)) ORDER BY key") {
        let key = r["key"]!!, value = r["value"]!!, desc = (r["description"] ?? "") ?? ""
        if !desc.isEmpty { out += "    /// \(desc)\n" }
        out += "    public static let \(camel(key)) = \(swiftString(value))\n"
    }
    out += "}\n"
    write("AppIdentity.swift", out)
}

// MARK: - ConnectPragmas.swift

do {
    var out = header("SQLite pragmas for every read-only connection (the `connect_pragma` table).")
    out += "import Foundation\n\n/// Applied in order to every read-only handle sqldoc opens.\npublic let sqldocConnectPragmas: [String] = [\n"
    for r in db.rows("SELECT name,value,rationale FROM connect_pragma WHERE platform IN ('all',\(swiftString(platform))) ORDER BY sort_order") {
        let name = r["name"]!!, value = r["value"]!!, why = (r["rationale"] ?? "") ?? ""
        out += "    \(swiftString("PRAGMA \(name) = \(value)")),\(why.isEmpty ? "" : "  // \(why)")\n"
    }
    out += "]\n"
    write("ConnectPragmas.swift", out)
}

// MARK: - DocConventions.swift

do {
    let rows = db.rows("SELECT name,kind,canonical,detail FROM doc_convention ORDER BY name")
    let prefix = rows.first(where: { ($0["name"] as? String) == "hidden-prefix" })?["canonical"] as? String ?? "_"
    var aliases: [(String, String)] = []
    var keys: [String] = []
    for r in rows {
        guard let kind = r["kind"] as? String, let name = r["name"] as? String else { continue }
        if kind == "style-key" { keys.append(name) }
        if kind == "style-key-alias", let canon = r["canonical"] as? String { aliases.append((name, canon)) }
    }
    var out = header("The self-describing-document contract (the `doc_convention` table).")
    out += "import Foundation\n\npublic enum DocConventions {\n"
    out += "    /// Tables whose name begins with this are hidden from the viewer.\n"
    out += "    public static let hiddenTablePrefix = \(swiftString(prefix))\n\n"
    out += "    /// Canonical keys accepted in a document's _style / _head table.\n"
    out += "    public static let styleKeys: Set<String> = [\(keys.map(swiftString).joined(separator: ", "))]\n\n"
    out += "    /// Alias -> canonical key, folded to lowercase before lookup.\n"
    out += "    public static let styleKeyAliases: [String: String] = [\n"
    for (a, c) in aliases { out += "        \(swiftString(a.lowercased())): \(swiftString(c)),\n" }
    out += "    ]\n}\n"
    write("DocConventions.swift", out)
}

// MARK: - Keybindings.swift  &  TypeRoles.swift

do {
    var out = header("Canonical keyboard shortcuts (the `keybinding` table). 'mod' = Command on macOS.")
    out += """
    import Foundation

    public struct SQLDocKeybinding: Sendable {
        public let action: String
        public let chord: String
        public let context: String
        public let label: String
    }

    public let sqldocKeybindings: [SQLDocKeybinding] = [

    """
    for r in db.rows("SELECT action,chord,context,label FROM keybinding WHERE platform IN ('all',\(swiftString(platform))) ORDER BY action") {
        out += "    SQLDocKeybinding(action: \(swiftString(r["action"]!!)), chord: \(swiftString(r["chord"]!!)), context: \(swiftString(r["context"]!!)), label: \(swiftString(r["label"]!!))),\n"
    }
    out += "]\n"
    write("Keybindings.swift", out)
}

do {
    var out = header("Typography roles (the `type_role` table).")
    out += """
    import CoreGraphics
    import Foundation

    public struct SQLDocTypeRole: Sendable {
        public let role: String
        public let isMonospaced: Bool
        public let sizePx: CGFloat
        public let weight: Int
        public let lineHeight: CGFloat
        public let trackingPx: CGFloat
        public let scalesWithZoom: Bool
    }

    public enum TypeRoles {
        public static let all: [SQLDocTypeRole] = [

    """
    for r in db.rows("SELECT role,font_family,size_px,weight,line_height,tracking_px,scales_with_zoom FROM type_role WHERE platform IN ('all',\(swiftString(platform))) ORDER BY role") {
        let mono = (r["font_family"]!! == "mono")
        out += "        SQLDocTypeRole(role: \(swiftString(r["role"]!!)), isMonospaced: \(mono), sizePx: \(numeric(r["size_px"]!!)), weight: \(r["weight"]!!), lineHeight: \(numeric(r["line_height"]!!)), trackingPx: \(numeric(r["tracking_px"]!!)), scalesWithZoom: \((r["scales_with_zoom"]!! == "1"))),\n"
    }
    out += "        ]\n\n"
    out += "    public static func role(_ name: String) -> SQLDocTypeRole? { all.first { $0.role == name } }\n}\n"
    write("TypeRoles.swift", out)
}

// MARK: - Info.plist (optional)

if !plistPath.isEmpty {
    var id: [String: String] = [:]
    for r in db.rows("SELECT key,value FROM v_identity WHERE platform=\(swiftString(platform))") {
        id[r["key"]!!] = r["value"]!!
    }
    func v(_ k: String, _ fallback: String = "") -> String { id[k] ?? fallback }
    let exts = v("doc_extensions").split(separator: ",").map {
        "        <string>\($0.trimmingCharacters(in: .whitespaces))</string>"
    }.joined(separator: "\n")

    let plist = """
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <!-- Generated by ConfigGen from sqldoc.db (schema v\(schemaVersion)). DO NOT EDIT. -->
    <plist version="1.0">
    <dict>
      <key>CFBundleExecutable</key>        <string>sqldoc</string>
      <key>CFBundleName</key>              <string>\(v("name"))</string>
      <key>CFBundleDisplayName</key>       <string>\(v("display_name", v("name")))</string>
      <key>CFBundleIdentifier</key>        <string>\(v("bundle_id"))</string>
      <key>CFBundleShortVersionString</key><string>\(v("version"))</string>
      <key>CFBundleVersion</key>           <string>\(v("build", "1"))</string>
      <key>CFBundlePackageType</key>       <string>APPL</string>
      <key>LSMinimumSystemVersion</key>    <string>\(v("macos_min_version", "14.0"))</string>
      <key>LSApplicationCategoryType</key> <string>\(v("category"))</string>
      <key>NSHumanReadableCopyright</key>  <string>\(v("copyright"))</string>
      <key>NSHighResolutionCapable</key>   <true/>
      <key>CFBundleIconFile</key>          <string>AppIcon</string>
      <key>CFBundleDocumentTypes</key>
      <array>
        <dict>
          <key>CFBundleTypeName</key>      <string>\(v("doc_type_name"))</string>
          <key>CFBundleTypeRole</key>      <string>Viewer</string>
          <key>LSHandlerRank</key>         <string>\(v("doc_handler_rank", "Alternate"))</string>
          <key>CFBundleTypeExtensions</key>
          <array>
    \(exts)
          </array>
        </dict>
      </array>
    </dict>
    </plist>

    """
    try? fm.createDirectory(atPath: (plistPath as NSString).deletingLastPathComponent, withIntermediateDirectories: true)
    try! plist.data(using: .utf8)!.write(to: URL(fileURLWithPath: plistPath))
    print("wrote \(plistPath)")
}

print("ConfigGen: done (\(platform), schema v\(schemaVersion))")
