#!/bin/sh
# gen-buildinfo.sh — stamp the current git revision into a Swift source file so
# the running app can show which build it is.
#
#   scripts/gen-buildinfo.sh [OUT]
#
# Rewrites OUT only when the content changes, so it does not churn the working
# tree on every build. Regenerated by `make build` / `make release` / `make app`;
# a plausible value is committed so a bare `swift build` still compiles.

set -eu

OUT="${1:-Sources/SQLDocCore/Generated/BuildInfo.swift}"

commit=$(git rev-parse --short=9 HEAD 2>/dev/null || echo "unknown")
commit_date=$(git show -s --format=%cs HEAD 2>/dev/null || echo "")
branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")

dirty=false
if ! git diff --quiet 2>/dev/null || ! git diff --cached --quiet 2>/dev/null; then
    dirty=true
fi

tmp=$(mktemp)
cat > "$tmp" <<EOF
// Generated by scripts/gen-buildinfo.sh. DO NOT EDIT.
// Stamped from git on every \`make build\`; a modified copy in the tree is
// expected and harmless (it just means you built since the last commit).
import Foundation

public enum BuildInfo {
    /// Short hash of HEAD when this binary was built.
    public static let commit = "$commit"
    /// Commit date of HEAD (YYYY-MM-DD).
    public static let commitDate = "$commit_date"
    /// Branch HEAD was on at build time.
    public static let branch = "$branch"
    /// True when the working tree had uncommitted changes at build time.
    public static let dirty = $dirty

    /// When this executable was actually built, read from its own file date.
    public static let builtAt: Date? = {
        guard let path = Bundle.main.executableURL?.path,
              let attrs = try? FileManager.default.attributesOfItem(atPath: path),
              let date = attrs[.modificationDate] as? Date else { return nil }
        return date
    }()

    /// e.g. "0.3.0 · a1b2c3d4e · built Aug 29, 14:32"
    public static var summary: String {
        var s = "\(AppIdentity.version) · \(commit)\(dirty ? "+" : "")"
        if let built = builtAt {
            let f = DateFormatter()
            f.dateFormat = "MMM d, HH:mm"
            s += " · built \(f.string(from: built))"
        }
        return s
    }

    /// Longer form for tooltips / the About panel.
    public static var detail: String {
        var parts = ["commit \(commit)\(dirty ? " (modified)" : "")"]
        if !branch.isEmpty, branch != "HEAD" { parts.append("branch \(branch)") }
        if !commitDate.isEmpty { parts.append(commitDate) }
        return parts.joined(separator: " · ")
    }
}
EOF

if ! cmp -s "$tmp" "$OUT" 2>/dev/null; then
    mv "$tmp" "$OUT"
    echo "wrote $OUT (commit $commit, dirty=$dirty)"
else
    rm -f "$tmp"
fi
